trigger: none
pr: none
schedules:
  - cron: "0 0 1 * *"
    displayName: Monthly build
    branches:
      include:
        - "*"
    always: true
jobs:
  - job: Build
    timeoutInMinutes: 0
    pool:
      vmImage: "macos-10.14"
    steps:
      - script: |
          brew cask install mactex-no-gui
          echo "##vso[task.prependpath]/Library/TeX/texbin"
        displayName: "Install MacTeX"
      - script: |
          sudo tlmgr update --self --all --reinstall-forcibly-removed
        displayName: "Update all TeX packages"
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.7"
      - script: |
          python -m pip install --upgrade pip setuptools wheel pipenv
        displayName: "Install Python tools"
      - script: |
          pipenv install
        displayName: "Install script dependencies"
      - script: |
          pipenv run python main.py
        displayName: "Build completion database"
      - publish: $(System.DefaultWorkingDirectory)/latex-completion-data.log
        artifact: latex-completion-data.log
      - powershell: |
          $version=$(Get-Date -Format "yy.MM");
          Write-Host "##vso[task.setvariable variable=calVer]$version"
        displayName: "Set release tag variable"
      - task: GitHubRelease@0
        inputs:
          gitHubConnection: latex-lsp
          repositoryName: latex-lsp/latex-completion-data
          assets: "$(System.DefaultWorkingDirectory)/completion.json"
          tagSource: "manual"
          tag: "$(calVer)"
        displayName: "Publish to GitHub"
